### ISSUE TITLE
NOTES & SUGGESTIONS 

### ISSUE THREAD

**Issue by xkajxkajx** [yutijang/M-Dl#1]
I like it so much and I have some suggestions if you please ?

![M-Dl](https://github.com/user-attachments/assets/81e889dd-7ea8-4e72-836d-f786e5509ec4)

**Comment by yutijang** [comment]
Hello @xkajxkajx 
Thank you for using this download tool and taking the time to write this issue report.

Here is the answer for you:
I have not or have yet to write a complete user guide on the repo. This is my fault.

* Regarding the 'Auto parse link in clipboard' feature, i have hidden it in this version. Along with it, features such as download multiple items in a playlist at once, up to 10 items can be downloaded at once (Playlist downloads simultaneously) and the Deep Packet Inspection circumvention utility (GoodbyeDPI) feature are also hidden in this version. They are in other versions, for example M-Dl Plus.
![1](https://github.com/user-attachments/assets/705d6233-5426-49e2-99da-51ee3fe35bce)

* The Queue button is used to add a link to the download queue, while the Add button is used to add a link to the list without downloading it.

They are distinguished by the background color of the download list: light green means the link is in the download queue, and no color means it is not waiting to download.
This feature is useful when you want to add some links to the download list but do not want to download them immediately. They can be downloaded later, whenever you want. The download list will be automatically saved when you close the tool, or you can manually save and load the list using the Save and Load buttons on the toolbar.

To add or remove one or more items from the download queue, select the item (or items), right-click on the selected item, a context menu will appear, and then select the corresponding option: "Add to queue" or "Remove from queue."

* In the Add single link button on the toolbar, you can only add one link at a time. Choose which type of download you want: Video, Audio, or Thumbnail, but not both or all three at the same time. If you want to download both video and audio, check the Video radio button and choose Queue or Add. Then, if you want audio, add the link again and choose the Audio radio button.

If you want to add multiple links for batch downloading, choose the Create link list button on the toolbar.

* In the video resolution list after parse, "BEST" means automatically select the highest possible resolution, which is equivalent to the last resolution in the resolution list.

* As you posted in the screenshot, I see there is a display error in the resolution list, the text lines should be centered like the following image, I will try to fix it, also because I don't have many operating systems with different configurations to test.
![2](https://github.com/user-attachments/assets/ee27ab74-4131-44a9-9973-8570ba75ea16)

Thanks you and good day!

**Comment by xkajxkajx** [comment]
Thanks for your kind elaborations . I get it now.

I think the clue to add "the video and the thumbnail link" at the same time is keeping the whole window open after pressing Queue\ Add. No need to paste the link twice.

![MDL2XX2](https://github.com/user-attachments/assets/eb42bed5-b2b1-4a72-94d5-59581e7c01f2)

I hope you get the idea!
Have a nice day!

**Comment by yutijang** [comment]
Thanks for your suggestion!

I have adjusted the "Add single link" and "Create link list" sections. Now, the window will remain open after pressing the "Queue" or "Add" button, allowing you to add more links or choose download types without having to reopen the window. You can press the "Close" button if you no longer want to add links.

As for the issue of missing text in some windows, I haven't identified the cause yet. It seems that the font size is larger than what I designed for, causing the text to be cut off at the end.

Have a good day to you!

**Comment by xkajxkajx** [comment]
Thank you much. Appreciate it.❤
You are a big help!
Never mind the missing text, I can live with it! 😄

**Comment by yutijang** [comment]
Hello,

Regarding the broken interface, it is related to an issue with DPI-awareness in the application. The system you are using may have changed the DPI by adjusting the 'Scale and Layout' settings (Change the size of text, apps, and other items) to 125% or 150%. If you adjust it to 100%, the design interface should no longer break. However, I cannot ask you to do that. This is a flaw in my design, and I will try to fix it.

Thanks you and have a good day to you!
